//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wardrobe.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WardrobeEntities : DbContext
    {
        public WardrobeEntities()
            : base("name=WardrobeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AccessoriesTable> AccessoriesTables { get; set; }
        public DbSet<BottomsTable> BottomsTables { get; set; }
        public DbSet<ProductsTable> ProductsTables { get; set; }
        public DbSet<ProductTypeTable> ProductTypeTables { get; set; }
        public DbSet<ShoesTable> ShoesTables { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TopsTable> TopsTables { get; set; }
    }
}
